# Generated by Django 4.0.6 on 2022-07-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookinstance_book_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ('status', '-due_back')},
        ),
    ]
