# Generated by Django 4.0.6 on 2022-07-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='authpic',
            field=models.ImageField(null=True, upload_to='authpics/'),
        ),
    ]
