# Generated by Django 4.0.6 on 2022-07-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
