# Generated by Django 4.0.6 on 2022-07-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_crud_authors', '#Create, Update and Delete authors'),)},
        ),
    ]
