# Generated by Django 4.0.6 on 2022-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_author_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authpic',
            field=models.ImageField(null=True, upload_to='authpics/', verbose_name='Photo'),
        ),
    ]
