# Generated by Django 4.0.6 on 2022-07-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_author_authpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authpic',
            field=models.ImageField(blank=True, null=True, upload_to='authpics/', verbose_name='Photo'),
        ),
    ]
