# Generated by Django 4.0.6 on 2022-07-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_author_authpic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-pubdate'], 'permissions': (('can_crud_books', 'Can create, update, and delete books'),)},
        ),
    ]
