# Generated by Django 4.0.6 on 2022-07-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarianGroupBasedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_librarian', 'This user is a Librarian'),),
            },
        ),
        migrations.CreateModel(
            name='LibraryMemberGroupBasedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('is_library_member', 'This user is a Library Member'),),
            },
        ),
    ]
