# Generated by Django 4.0.6 on 2022-07-16 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_librariangroupbasedpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-pubdate'], 'permissions': (('can_crud_books', 'Can create, update, and delete books'), ('can_view_detailed_books', 'DETAIL VIEW PERMISSION'))},
        ),
    ]
