# Generated by Django 4.0.6 on 2022-07-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', '-pubdate'], 'permissions': (('can_crud_books', 'Can create, update, and delete books'),)},
        ),
    ]
