# Generated by Django 4.0.6 on 2022-07-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_author_date_of_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'On loan'), ('a', 'Available')], default='a', help_text='Book availability', max_length=1),
        ),
    ]
